# Generated by Django 6.1.1 on 2026-09-23 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('PTM', 'Parent-Teacher Meeting'), ('HOLIDAY', 'Holiday'), ('EXAM', 'Exam'), ('ACTIVITY', 'Activity'), ('OTHER', 'Other')], max_length=10)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('school_class', models.ForeignKey(blank=True, help_text='Leave blank for a school-wide event', null=True, on_delete=django.db.models.deletion.CASCADE, to='students.schoolclass')),
            ],
        ),
    ]
